/*
 * SPDX-FileCopyrightText: 2025 David Jolly <jolly.a.david@gmail.com>
 * SPDX-License-Identifier: MIT
 */

#ifndef CGBL_PROCESSOR_H_
#define CGBL_PROCESSOR_H_

#include "bus.h"

#define CGBL_PROCESSOR_INTERRUPT_ENABLE 0xFFFF
#define CGBL_PROCESSOR_INTERRUPT_FLAG 0xFF0F

typedef enum {
    CGBL_INSTRUCTION_ADC_A = 0x8F, CGBL_INSTRUCTION_ADC_B = 0x88, CGBL_INSTRUCTION_ADC_C = 0x89, CGBL_INSTRUCTION_ADC_D = 0x8A,
    CGBL_INSTRUCTION_ADC_E = 0x8B, CGBL_INSTRUCTION_ADC_H = 0x8C, CGBL_INSTRUCTION_ADC_HLI = 0x8E, CGBL_INSTRUCTION_ADC_L = 0x8D,
    CGBL_INSTRUCTION_ADC_N = 0xCE,
    CGBL_INSTRUCTION_ADD_A = 0x87, CGBL_INSTRUCTION_ADD_B = 0x80, CGBL_INSTRUCTION_ADD_C = 0x81, CGBL_INSTRUCTION_ADD_D = 0x82,
    CGBL_INSTRUCTION_ADD_E = 0x83, CGBL_INSTRUCTION_ADD_H = 0x84, CGBL_INSTRUCTION_ADD_HL_BC = 0x09, CGBL_INSTRUCTION_ADD_HL_DE = 0x19,
    CGBL_INSTRUCTION_ADD_HL_HL = 0x29, CGBL_INSTRUCTION_ADD_HL_SP = 0x39, CGBL_INSTRUCTION_ADD_HLI = 0x86, CGBL_INSTRUCTION_ADD_L = 0x85,
    CGBL_INSTRUCTION_ADD_N = 0xC6,
    CGBL_INSTRUCTION_AND_A = 0xA7, CGBL_INSTRUCTION_AND_B = 0xA0, CGBL_INSTRUCTION_AND_C = 0xA1, CGBL_INSTRUCTION_AND_D = 0xA2,
    CGBL_INSTRUCTION_AND_E = 0xA3, CGBL_INSTRUCTION_AND_H = 0xA4, CGBL_INSTRUCTION_AND_HLI = 0xA6, CGBL_INSTRUCTION_AND_L = 0xA5,
    CGBL_INSTRUCTION_AND_N = 0xE6,
    CGBL_INSTRUCTION_BIT_0_A = 0x47, CGBL_INSTRUCTION_BIT_0_B = 0x40, CGBL_INSTRUCTION_BIT_0_C = 0x41, CGBL_INSTRUCTION_BIT_0_D = 0x42,
    CGBL_INSTRUCTION_BIT_0_E = 0x43, CGBL_INSTRUCTION_BIT_0_H = 0x44, CGBL_INSTRUCTION_BIT_0_HLI = 0x46, CGBL_INSTRUCTION_BIT_0_L = 0x45,
    CGBL_INSTRUCTION_BIT_1_A = 0x4F, CGBL_INSTRUCTION_BIT_1_B = 0x48, CGBL_INSTRUCTION_BIT_1_C = 0x49, CGBL_INSTRUCTION_BIT_1_D = 0x4A,
    CGBL_INSTRUCTION_BIT_1_E = 0x4B, CGBL_INSTRUCTION_BIT_1_H = 0x4C, CGBL_INSTRUCTION_BIT_1_HLI = 0x4E, CGBL_INSTRUCTION_BIT_1_L = 0x4D,
    CGBL_INSTRUCTION_BIT_2_A = 0x57, CGBL_INSTRUCTION_BIT_2_B = 0x50, CGBL_INSTRUCTION_BIT_2_C = 0x51, CGBL_INSTRUCTION_BIT_2_D = 0x52,
    CGBL_INSTRUCTION_BIT_2_E = 0x53, CGBL_INSTRUCTION_BIT_2_H = 0x54, CGBL_INSTRUCTION_BIT_2_HLI = 0x56, CGBL_INSTRUCTION_BIT_2_L = 0x55,
    CGBL_INSTRUCTION_BIT_3_A = 0x5F, CGBL_INSTRUCTION_BIT_3_B = 0x58, CGBL_INSTRUCTION_BIT_3_C = 0x59, CGBL_INSTRUCTION_BIT_3_D = 0x5A,
    CGBL_INSTRUCTION_BIT_3_E = 0x5B, CGBL_INSTRUCTION_BIT_3_H = 0x5C, CGBL_INSTRUCTION_BIT_3_HLI = 0x5E, CGBL_INSTRUCTION_BIT_3_L = 0x5D,
    CGBL_INSTRUCTION_BIT_4_A = 0x67, CGBL_INSTRUCTION_BIT_4_B = 0x60, CGBL_INSTRUCTION_BIT_4_C = 0x61, CGBL_INSTRUCTION_BIT_4_D = 0x62,
    CGBL_INSTRUCTION_BIT_4_E = 0x63, CGBL_INSTRUCTION_BIT_4_H = 0x64, CGBL_INSTRUCTION_BIT_4_HLI = 0x66, CGBL_INSTRUCTION_BIT_4_L = 0x65,
    CGBL_INSTRUCTION_BIT_5_A = 0x6F, CGBL_INSTRUCTION_BIT_5_B = 0x68, CGBL_INSTRUCTION_BIT_5_C = 0x69, CGBL_INSTRUCTION_BIT_5_D = 0x6A,
    CGBL_INSTRUCTION_BIT_5_E = 0x6B, CGBL_INSTRUCTION_BIT_5_H = 0x6C, CGBL_INSTRUCTION_BIT_5_HLI = 0x6E, CGBL_INSTRUCTION_BIT_5_L = 0x6D,
    CGBL_INSTRUCTION_BIT_6_A = 0x77, CGBL_INSTRUCTION_BIT_6_B = 0x70, CGBL_INSTRUCTION_BIT_6_C = 0x71, CGBL_INSTRUCTION_BIT_6_D = 0x72,
    CGBL_INSTRUCTION_BIT_6_E = 0x73, CGBL_INSTRUCTION_BIT_6_H = 0x74, CGBL_INSTRUCTION_BIT_6_HLI = 0x76, CGBL_INSTRUCTION_BIT_6_L = 0x75,
    CGBL_INSTRUCTION_BIT_7_A = 0x7F, CGBL_INSTRUCTION_BIT_7_B = 0x78, CGBL_INSTRUCTION_BIT_7_C = 0x79, CGBL_INSTRUCTION_BIT_7_D = 0x7A,
    CGBL_INSTRUCTION_BIT_7_E = 0x7B, CGBL_INSTRUCTION_BIT_7_H = 0x7C, CGBL_INSTRUCTION_BIT_7_HLI = 0x7E, CGBL_INSTRUCTION_BIT_7_L = 0x7D,
    CGBL_INSTRUCTION_CALL = 0xCD, CGBL_INSTRUCTION_CALL_C = 0xDC, CGBL_INSTRUCTION_CALL_NC = 0xD4, CGBL_INSTRUCTION_CALL_NZ = 0xC4,
    CGBL_INSTRUCTION_CALL_Z = 0xCC,
    CGBL_INSTRUCTION_CP_A = 0xBF, CGBL_INSTRUCTION_CP_B = 0xB8, CGBL_INSTRUCTION_CP_C = 0xB9, CGBL_INSTRUCTION_CP_D = 0xBA,
    CGBL_INSTRUCTION_CP_E = 0xBB, CGBL_INSTRUCTION_CP_H = 0xBC, CGBL_INSTRUCTION_CP_HLI = 0xBE, CGBL_INSTRUCTION_CP_L = 0xBD,
    CGBL_INSTRUCTION_CP_N = 0xFE,
    CGBL_INSTRUCTION_DEC_A = 0x3D, CGBL_INSTRUCTION_DEC_B = 0x05, CGBL_INSTRUCTION_DEC_BC = 0x0B, CGBL_INSTRUCTION_DEC_C = 0x0D,
    CGBL_INSTRUCTION_DEC_D = 0x15, CGBL_INSTRUCTION_DEC_DE = 0x1B, CGBL_INSTRUCTION_DEC_E = 0x1D, CGBL_INSTRUCTION_DEC_H = 0x25,
    CGBL_INSTRUCTION_DEC_HL = 0x2B, CGBL_INSTRUCTION_DEC_HLI = 0x35, CGBL_INSTRUCTION_DEC_L = 0x2D, CGBL_INSTRUCTION_DEC_SP = 0x3B,
    CGBL_INSTRUCTION_INC_A = 0x3C, CGBL_INSTRUCTION_INC_B = 0x04, CGBL_INSTRUCTION_INC_BC = 0x03, CGBL_INSTRUCTION_INC_C = 0x0C,
    CGBL_INSTRUCTION_INC_D = 0x14, CGBL_INSTRUCTION_INC_DE = 0x13, CGBL_INSTRUCTION_INC_E = 0x1C, CGBL_INSTRUCTION_INC_H = 0x24,
    CGBL_INSTRUCTION_INC_HL = 0x23, CGBL_INSTRUCTION_INC_HLI = 0x34, CGBL_INSTRUCTION_INC_L = 0x2C, CGBL_INSTRUCTION_INC_SP = 0x33,
    CGBL_INSTRUCTION_JP = 0xC3, CGBL_INSTRUCTION_JP_C = 0xDA, CGBL_INSTRUCTION_JP_NC = 0xD2, CGBL_INSTRUCTION_JP_NZ = 0xC2,
    CGBL_INSTRUCTION_JP_Z = 0xCA,
    CGBL_INSTRUCTION_JR = 0x18, CGBL_INSTRUCTION_JR_C = 0x38, CGBL_INSTRUCTION_JR_NC = 0x30, CGBL_INSTRUCTION_JR_NZ = 0x20,
    CGBL_INSTRUCTION_JR_Z = 0x28,
    CGBL_INSTRUCTION_LD_A_A = 0x7F, CGBL_INSTRUCTION_LD_A_B = 0x78, CGBL_INSTRUCTION_LD_A_BCI = 0x0A, CGBL_INSTRUCTION_LD_A_C = 0x79,
    CGBL_INSTRUCTION_LD_A_D = 0x7A, CGBL_INSTRUCTION_LD_A_DEI = 0x1A, CGBL_INSTRUCTION_LD_A_E = 0x7B, CGBL_INSTRUCTION_LD_A_H = 0x7C,
    CGBL_INSTRUCTION_LD_A_HLI = 0x7E, CGBL_INSTRUCTION_LD_A_HLID = 0x3A, CGBL_INSTRUCTION_LD_A_HLII = 0x2A, CGBL_INSTRUCTION_LD_A_L = 0x7D,
    CGBL_INSTRUCTION_LD_A_N = 0x3E, CGBL_INSTRUCTION_LD_A_NNI = 0xFA, CGBL_INSTRUCTION_LD_A_FF00_CI = 0xF2, CGBL_INSTRUCTION_LD_A_FF00_NI = 0xF0,
    CGBL_INSTRUCTION_LD_B_A = 0x47, CGBL_INSTRUCTION_LD_B_B = 0x40, CGBL_INSTRUCTION_LD_B_C = 0x41, CGBL_INSTRUCTION_LD_B_D = 0x42,
    CGBL_INSTRUCTION_LD_B_E = 0x43, CGBL_INSTRUCTION_LD_B_H = 0x44, CGBL_INSTRUCTION_LD_B_HLI = 0x46, CGBL_INSTRUCTION_LD_B_L = 0x45,
    CGBL_INSTRUCTION_LD_B_N = 0x06, CGBL_INSTRUCTION_LD_BC_NN = 0x01, CGBL_INSTRUCTION_LD_BCI_A = 0x02, CGBL_INSTRUCTION_LD_C_A = 0x4F,
    CGBL_INSTRUCTION_LD_C_B = 0x48, CGBL_INSTRUCTION_LD_C_C = 0x49, CGBL_INSTRUCTION_LD_C_D = 0x4A, CGBL_INSTRUCTION_LD_C_E = 0x4B,
    CGBL_INSTRUCTION_LD_C_H = 0x4C, CGBL_INSTRUCTION_LD_C_HLI = 0x4E, CGBL_INSTRUCTION_LD_C_L = 0x4D, CGBL_INSTRUCTION_LD_C_N = 0x0E,
    CGBL_INSTRUCTION_LD_D_A = 0x57, CGBL_INSTRUCTION_LD_D_B = 0x50, CGBL_INSTRUCTION_LD_D_C = 0x51, CGBL_INSTRUCTION_LD_D_D = 0x52,
    CGBL_INSTRUCTION_LD_D_E = 0x53, CGBL_INSTRUCTION_LD_D_H = 0x54, CGBL_INSTRUCTION_LD_D_HLI = 0x56, CGBL_INSTRUCTION_LD_D_L = 0x55,
    CGBL_INSTRUCTION_LD_D_N = 0x16, CGBL_INSTRUCTION_LD_DE_NN = 0x11, CGBL_INSTRUCTION_LD_DEI_A = 0x12, CGBL_INSTRUCTION_LD_E_A = 0x5F,
    CGBL_INSTRUCTION_LD_E_B = 0x58, CGBL_INSTRUCTION_LD_E_C = 0x59, CGBL_INSTRUCTION_LD_E_D = 0x5A, CGBL_INSTRUCTION_LD_E_E = 0x5B,
    CGBL_INSTRUCTION_LD_E_H = 0x5C, CGBL_INSTRUCTION_LD_E_HLI = 0x5E, CGBL_INSTRUCTION_LD_E_L = 0x5D, CGBL_INSTRUCTION_LD_E_N = 0x1E,
    CGBL_INSTRUCTION_LD_FF00_CI_A = 0xE2, CGBL_INSTRUCTION_LD_FF00_NI_A = 0xE0, CGBL_INSTRUCTION_LD_H_A = 0x67, CGBL_INSTRUCTION_LD_H_B = 0x60,
    CGBL_INSTRUCTION_LD_H_C = 0x61, CGBL_INSTRUCTION_LD_H_D = 0x62, CGBL_INSTRUCTION_LD_H_E = 0x63, CGBL_INSTRUCTION_LD_H_H = 0x64,
    CGBL_INSTRUCTION_LD_H_HLI = 0x66, CGBL_INSTRUCTION_LD_H_L = 0x65, CGBL_INSTRUCTION_LD_H_N = 0x26, CGBL_INSTRUCTION_LD_HL_NN = 0x21,
    CGBL_INSTRUCTION_LD_HLI_A = 0x77, CGBL_INSTRUCTION_LD_HLI_B = 0x70, CGBL_INSTRUCTION_LD_HLI_C = 0x71, CGBL_INSTRUCTION_LD_HLI_D = 0x72,
    CGBL_INSTRUCTION_LD_HLI_E = 0x73, CGBL_INSTRUCTION_LD_HLI_H = 0x74, CGBL_INSTRUCTION_LD_HLI_L = 0x75, CGBL_INSTRUCTION_LD_HLI_N = 0x36,
    CGBL_INSTRUCTION_LD_HLID_A = 0x32, CGBL_INSTRUCTION_LD_HLII_A = 0x22, CGBL_INSTRUCTION_LD_L_A = 0x6F, CGBL_INSTRUCTION_LD_L_B = 0x68,
    CGBL_INSTRUCTION_LD_L_C = 0x69, CGBL_INSTRUCTION_LD_L_D = 0x6A, CGBL_INSTRUCTION_LD_L_E = 0x6B, CGBL_INSTRUCTION_LD_L_H = 0x6C,
    CGBL_INSTRUCTION_LD_L_HLI = 0x6E, CGBL_INSTRUCTION_LD_L_L = 0x6D, CGBL_INSTRUCTION_LD_L_N = 0x2E, CGBL_INSTRUCTION_LD_NNI_A = 0xEA,
    CGBL_INSTRUCTION_LD_NNI_SP = 0x08, CGBL_INSTRUCTION_LD_SP_HL = 0xF9, CGBL_INSTRUCTION_LD_SP_NN = 0x31,
    CGBL_INSTRUCTION_OR_A = 0xB7, CGBL_INSTRUCTION_OR_B = 0xB0, CGBL_INSTRUCTION_OR_C = 0xB1, CGBL_INSTRUCTION_OR_D = 0xB2,
    CGBL_INSTRUCTION_OR_E = 0xB3, CGBL_INSTRUCTION_OR_H = 0xB4, CGBL_INSTRUCTION_OR_HLI = 0xB6, CGBL_INSTRUCTION_OR_L = 0xB5,
    CGBL_INSTRUCTION_OR_N = 0xF6,
    CGBL_INSTRUCTION_POP_AF = 0xF1, CGBL_INSTRUCTION_POP_BC = 0xC1, CGBL_INSTRUCTION_POP_DE = 0xD1, CGBL_INSTRUCTION_POP_HL = 0xE1,
    CGBL_INSTRUCTION_PUSH_AF = 0xF5, CGBL_INSTRUCTION_PUSH_BC = 0xC5, CGBL_INSTRUCTION_PUSH_DE = 0xD5, CGBL_INSTRUCTION_PUSH_HL = 0xE5,
    CGBL_INSTRUCTION_RES_0_A = 0x87, CGBL_INSTRUCTION_RES_0_B = 0x80, CGBL_INSTRUCTION_RES_0_C = 0x81, CGBL_INSTRUCTION_RES_0_D = 0x82,
    CGBL_INSTRUCTION_RES_0_E = 0x83, CGBL_INSTRUCTION_RES_0_H = 0x84, CGBL_INSTRUCTION_RES_0_HLI = 0x86, CGBL_INSTRUCTION_RES_0_L = 0x85,
    CGBL_INSTRUCTION_RES_1_A = 0x8F, CGBL_INSTRUCTION_RES_1_B = 0x88, CGBL_INSTRUCTION_RES_1_C = 0x89, CGBL_INSTRUCTION_RES_1_D = 0x8A,
    CGBL_INSTRUCTION_RES_1_E = 0x8B, CGBL_INSTRUCTION_RES_1_H = 0x8C, CGBL_INSTRUCTION_RES_1_HLI = 0x8E, CGBL_INSTRUCTION_RES_1_L = 0x8D,
    CGBL_INSTRUCTION_RES_2_A = 0x97, CGBL_INSTRUCTION_RES_2_B = 0x90, CGBL_INSTRUCTION_RES_2_C = 0x91, CGBL_INSTRUCTION_RES_2_D = 0x92,
    CGBL_INSTRUCTION_RES_2_E = 0x93, CGBL_INSTRUCTION_RES_2_H = 0x94, CGBL_INSTRUCTION_RES_2_HLI = 0x96, CGBL_INSTRUCTION_RES_2_L = 0x95,
    CGBL_INSTRUCTION_RES_3_A = 0x9F, CGBL_INSTRUCTION_RES_3_B = 0x98, CGBL_INSTRUCTION_RES_3_C = 0x99, CGBL_INSTRUCTION_RES_3_D = 0x9A,
    CGBL_INSTRUCTION_RES_3_E = 0x9B, CGBL_INSTRUCTION_RES_3_H = 0x9C, CGBL_INSTRUCTION_RES_3_HLI = 0x9E, CGBL_INSTRUCTION_RES_3_L = 0x9D,
    CGBL_INSTRUCTION_RES_4_A = 0xA7, CGBL_INSTRUCTION_RES_4_B = 0xA0, CGBL_INSTRUCTION_RES_4_C = 0xA1, CGBL_INSTRUCTION_RES_4_D = 0xA2,
    CGBL_INSTRUCTION_RES_4_E = 0xA3, CGBL_INSTRUCTION_RES_4_H = 0xA4, CGBL_INSTRUCTION_RES_4_HLI = 0xA6, CGBL_INSTRUCTION_RES_4_L = 0xA5,
    CGBL_INSTRUCTION_RES_5_A = 0xAF, CGBL_INSTRUCTION_RES_5_B = 0xA8, CGBL_INSTRUCTION_RES_5_C = 0xA9, CGBL_INSTRUCTION_RES_5_D = 0xAA,
    CGBL_INSTRUCTION_RES_5_E = 0xAB, CGBL_INSTRUCTION_RES_5_H = 0xAC, CGBL_INSTRUCTION_RES_5_HLI = 0xAE, CGBL_INSTRUCTION_RES_5_L = 0xAD,
    CGBL_INSTRUCTION_RES_6_A = 0xB7, CGBL_INSTRUCTION_RES_6_B = 0xB0, CGBL_INSTRUCTION_RES_6_C = 0xB1, CGBL_INSTRUCTION_RES_6_D = 0xB2,
    CGBL_INSTRUCTION_RES_6_E = 0xB3, CGBL_INSTRUCTION_RES_6_H = 0xB4, CGBL_INSTRUCTION_RES_6_HLI = 0xB6, CGBL_INSTRUCTION_RES_6_L = 0xB5,
    CGBL_INSTRUCTION_RES_7_A = 0xBF, CGBL_INSTRUCTION_RES_7_B = 0xB8, CGBL_INSTRUCTION_RES_7_C = 0xB9, CGBL_INSTRUCTION_RES_7_D = 0xBA,
    CGBL_INSTRUCTION_RES_7_E = 0xBB, CGBL_INSTRUCTION_RES_7_H = 0xBC, CGBL_INSTRUCTION_RES_7_HLI = 0xBE, CGBL_INSTRUCTION_RES_7_L = 0xBD,
    CGBL_INSTRUCTION_RL_A = 0x17, CGBL_INSTRUCTION_RL_B = 0x10, CGBL_INSTRUCTION_RL_C = 0x11, CGBL_INSTRUCTION_RL_D = 0x12,
    CGBL_INSTRUCTION_RL_E = 0x13, CGBL_INSTRUCTION_RL_H = 0x14, CGBL_INSTRUCTION_RL_HLI = 0x16, CGBL_INSTRUCTION_RL_L = 0x15,
    CGBL_INSTRUCTION_RLC_A = 0x07, CGBL_INSTRUCTION_RLC_B = 0x00, CGBL_INSTRUCTION_RLC_C = 0x01, CGBL_INSTRUCTION_RLC_D = 0x02,
    CGBL_INSTRUCTION_RLC_E = 0x03, CGBL_INSTRUCTION_RLC_H = 0x04, CGBL_INSTRUCTION_RLC_HLI = 0x06, CGBL_INSTRUCTION_RLC_L = 0x05,
    CGBL_INSTRUCTION_RR_A = 0x1F, CGBL_INSTRUCTION_RR_B = 0x18, CGBL_INSTRUCTION_RR_C = 0x19, CGBL_INSTRUCTION_RR_D = 0x1A,
    CGBL_INSTRUCTION_RR_E = 0x1B, CGBL_INSTRUCTION_RR_H = 0x1C, CGBL_INSTRUCTION_RR_HLI = 0x1E, CGBL_INSTRUCTION_RR_L = 0x1D,
    CGBL_INSTRUCTION_RRC_A = 0x0F, CGBL_INSTRUCTION_RRC_B = 0x08, CGBL_INSTRUCTION_RRC_C = 0x09, CGBL_INSTRUCTION_RRC_D = 0x0A,
    CGBL_INSTRUCTION_RRC_E = 0x0B, CGBL_INSTRUCTION_RRC_H = 0x0C, CGBL_INSTRUCTION_RRC_HLI = 0x0E, CGBL_INSTRUCTION_RRC_L = 0x0D,
    CGBL_INSTRUCTION_RET = 0xC9, CGBL_INSTRUCTION_RET_C = 0xD8, CGBL_INSTRUCTION_RET_NC = 0xD0, CGBL_INSTRUCTION_RET_NZ = 0xC0,
    CGBL_INSTRUCTION_RET_Z = 0xC8,
    CGBL_INSTRUCTION_RST_00 = 0xC7,
    CGBL_INSTRUCTION_SBC_A = 0x9F, CGBL_INSTRUCTION_SBC_B = 0x98, CGBL_INSTRUCTION_SBC_C = 0x99, CGBL_INSTRUCTION_SBC_D = 0x9A,
    CGBL_INSTRUCTION_SBC_E = 0x9B, CGBL_INSTRUCTION_SBC_H = 0x9C, CGBL_INSTRUCTION_SBC_HLI = 0x9E, CGBL_INSTRUCTION_SBC_L = 0x9D,
    CGBL_INSTRUCTION_SBC_N = 0xDE,
    CGBL_INSTRUCTION_SET_0_A = 0xC7, CGBL_INSTRUCTION_SET_0_B = 0xC0, CGBL_INSTRUCTION_SET_0_C = 0xC1, CGBL_INSTRUCTION_SET_0_D = 0xC2,
    CGBL_INSTRUCTION_SET_0_E = 0xC3, CGBL_INSTRUCTION_SET_0_H = 0xC4, CGBL_INSTRUCTION_SET_0_HLI = 0xC6, CGBL_INSTRUCTION_SET_0_L = 0xC5,
    CGBL_INSTRUCTION_SET_1_A = 0xCF, CGBL_INSTRUCTION_SET_1_B = 0xC8, CGBL_INSTRUCTION_SET_1_C = 0xC9, CGBL_INSTRUCTION_SET_1_D = 0xCA,
    CGBL_INSTRUCTION_SET_1_E = 0xCB, CGBL_INSTRUCTION_SET_1_H = 0xCC, CGBL_INSTRUCTION_SET_1_HLI = 0xCE, CGBL_INSTRUCTION_SET_1_L = 0xCD,
    CGBL_INSTRUCTION_SET_2_A = 0xD7, CGBL_INSTRUCTION_SET_2_B = 0xD0, CGBL_INSTRUCTION_SET_2_C = 0xD1, CGBL_INSTRUCTION_SET_2_D = 0xD2,
    CGBL_INSTRUCTION_SET_2_E = 0xD3, CGBL_INSTRUCTION_SET_2_H = 0xD4, CGBL_INSTRUCTION_SET_2_HLI = 0xD6, CGBL_INSTRUCTION_SET_2_L = 0xD5,
    CGBL_INSTRUCTION_SET_3_A = 0xDF, CGBL_INSTRUCTION_SET_3_B = 0xD8, CGBL_INSTRUCTION_SET_3_C = 0xD9, CGBL_INSTRUCTION_SET_3_D = 0xDA,
    CGBL_INSTRUCTION_SET_3_E = 0xDB, CGBL_INSTRUCTION_SET_3_H = 0xDC, CGBL_INSTRUCTION_SET_3_HLI = 0xDE, CGBL_INSTRUCTION_SET_3_L = 0xDD,
    CGBL_INSTRUCTION_SET_4_A = 0xE7, CGBL_INSTRUCTION_SET_4_B = 0xE0, CGBL_INSTRUCTION_SET_4_C = 0xE1, CGBL_INSTRUCTION_SET_4_D = 0xE2,
    CGBL_INSTRUCTION_SET_4_E = 0xE3, CGBL_INSTRUCTION_SET_4_H = 0xE4, CGBL_INSTRUCTION_SET_4_HLI = 0xE6, CGBL_INSTRUCTION_SET_4_L = 0xE5,
    CGBL_INSTRUCTION_SET_5_A = 0xEF, CGBL_INSTRUCTION_SET_5_B = 0xE8, CGBL_INSTRUCTION_SET_5_C = 0xE9, CGBL_INSTRUCTION_SET_5_D = 0xEA,
    CGBL_INSTRUCTION_SET_5_E = 0xEB, CGBL_INSTRUCTION_SET_5_H = 0xEC, CGBL_INSTRUCTION_SET_5_HLI = 0xEE, CGBL_INSTRUCTION_SET_5_L = 0xED,
    CGBL_INSTRUCTION_SET_6_A = 0xF7, CGBL_INSTRUCTION_SET_6_B = 0xF0, CGBL_INSTRUCTION_SET_6_C = 0xF1, CGBL_INSTRUCTION_SET_6_D = 0xF2,
    CGBL_INSTRUCTION_SET_6_E = 0xF3, CGBL_INSTRUCTION_SET_6_H = 0xF4, CGBL_INSTRUCTION_SET_6_HLI = 0xF6, CGBL_INSTRUCTION_SET_6_L = 0xF5,
    CGBL_INSTRUCTION_SET_7_A = 0xFF, CGBL_INSTRUCTION_SET_7_B = 0xF8, CGBL_INSTRUCTION_SET_7_C = 0xF9, CGBL_INSTRUCTION_SET_7_D = 0xFA,
    CGBL_INSTRUCTION_SET_7_E = 0xFB, CGBL_INSTRUCTION_SET_7_H = 0xFC, CGBL_INSTRUCTION_SET_7_HLI = 0xFE, CGBL_INSTRUCTION_SET_7_L = 0xFD,
    CGBL_INSTRUCTION_SLA_A = 0x27, CGBL_INSTRUCTION_SLA_B = 0x20, CGBL_INSTRUCTION_SLA_C = 0x21, CGBL_INSTRUCTION_SLA_D = 0x22,
    CGBL_INSTRUCTION_SLA_E = 0x23, CGBL_INSTRUCTION_SLA_H = 0x24, CGBL_INSTRUCTION_SLA_HLI = 0x26, CGBL_INSTRUCTION_SLA_L = 0x25,
    CGBL_INSTRUCTION_SRA_A = 0x2F, CGBL_INSTRUCTION_SRA_B = 0x28, CGBL_INSTRUCTION_SRA_C = 0x29, CGBL_INSTRUCTION_SRA_D = 0x2A,
    CGBL_INSTRUCTION_SRA_E = 0x2B, CGBL_INSTRUCTION_SRA_H = 0x2C, CGBL_INSTRUCTION_SRA_HLI = 0x2E, CGBL_INSTRUCTION_SRA_L = 0x2D,
    CGBL_INSTRUCTION_SRL_A = 0x3F, CGBL_INSTRUCTION_SRL_B = 0x38, CGBL_INSTRUCTION_SRL_C = 0x39, CGBL_INSTRUCTION_SRL_D = 0x3A,
    CGBL_INSTRUCTION_SRL_E = 0x3B, CGBL_INSTRUCTION_SRL_H = 0x3C, CGBL_INSTRUCTION_SRL_HLI = 0x3E, CGBL_INSTRUCTION_SRL_L = 0x3D,
    CGBL_INSTRUCTION_SUB_A = 0x97, CGBL_INSTRUCTION_SUB_B = 0x90, CGBL_INSTRUCTION_SUB_C = 0x91, CGBL_INSTRUCTION_SUB_D = 0x92,
    CGBL_INSTRUCTION_SUB_E = 0x93, CGBL_INSTRUCTION_SUB_H = 0x94, CGBL_INSTRUCTION_SUB_HLI = 0x96, CGBL_INSTRUCTION_SUB_L = 0x95,
    CGBL_INSTRUCTION_SUB_N = 0xD6,
    CGBL_INSTRUCTION_SWAP_A = 0x37, CGBL_INSTRUCTION_SWAP_B = 0x30, CGBL_INSTRUCTION_SWAP_C = 0x31, CGBL_INSTRUCTION_SWAP_D = 0x32,
    CGBL_INSTRUCTION_SWAP_E = 0x33, CGBL_INSTRUCTION_SWAP_H = 0x34, CGBL_INSTRUCTION_SWAP_HLI = 0x36, CGBL_INSTRUCTION_SWAP_L = 0x35,
    CGBL_INSTRUCTION_XOR_A = 0xAF, CGBL_INSTRUCTION_XOR_B = 0xA8, CGBL_INSTRUCTION_XOR_C = 0xA9, CGBL_INSTRUCTION_XOR_D = 0xAA,
    CGBL_INSTRUCTION_XOR_E = 0xAB, CGBL_INSTRUCTION_XOR_H = 0xAC, CGBL_INSTRUCTION_XOR_HLI = 0xAE, CGBL_INSTRUCTION_XOR_L = 0xAD,
    CGBL_INSTRUCTION_XOR_N = 0xEE,
    CGBL_INSTRUCTION_PREFIX = 0xCB,
    CGBL_INSTRUCTION_MAX = 256,
} cgbl_instruction_e;

typedef enum {
    CGBL_INTERRUPT_VBLANK = 0,
    CGBL_INTERRUPT_SCREEN,
    CGBL_INTERRUPT_TIMER,
    CGBL_INTERRUPT_SERIAL,
    CGBL_INTERRUPT_INPUT,
    CGBL_INTERRUPT_MAX,
} cgbl_interrupt_e;

typedef enum {
    CGBL_REGISTER_A = 0,
    CGBL_REGISTER_AF,
    CGBL_REGISTER_B,
    CGBL_REGISTER_BC,
    CGBL_REGISTER_C,
    CGBL_REGISTER_D,
    CGBL_REGISTER_DE,
    CGBL_REGISTER_E,
    CGBL_REGISTER_F,
    CGBL_REGISTER_H,
    CGBL_REGISTER_HL,
    CGBL_REGISTER_L,
    CGBL_REGISTER_PC,
    CGBL_REGISTER_SP,
    CGBL_REGISTER_MAX,
} cgbl_register_e;

typedef union {
    struct {
        union {
            struct {
                uint8_t : 4;
                uint8_t carry : 1;
                uint8_t half_carry : 1;
                uint8_t negative : 1;
                uint8_t zero : 1;
            };
            uint8_t low;
        };
        uint8_t high;
    };
    uint16_t word;
} cgbl_register_t;

bool cgbl_processor_halted(void);
void cgbl_processor_interrupt(cgbl_interrupt_e interrupt);
cgbl_error_e cgbl_processor_register_read(cgbl_register_e reg, cgbl_register_t *const data);
cgbl_error_e cgbl_processor_register_write(cgbl_register_e reg, const cgbl_register_t *const data);
uint8_t cgbl_processor_read(uint16_t address);
void cgbl_processor_reset(void);
cgbl_error_e cgbl_processor_step(void);
cgbl_error_e cgbl_processor_step_breakpoint(uint16_t breakpoint);
bool cgbl_processor_stopped(void);
void cgbl_processor_write(uint16_t address, uint8_t data);

#endif /* CGBL_PROCESSOR_H_ */
