/*
 * SPDX-FileCopyrightText: 2025 David Jolly <jolly.a.david@gmail.com>
 * SPDX-License-Identifier: MIT
 */

#ifndef CGBL_VIDEO_H_
#define CGBL_VIDEO_H_

#include "bus.h"

#define CGBL_VIDEO_CONTROL 0xFF40
#define CGBL_VIDEO_HEIGHT 144
#define CGBL_VIDEO_LINE_Y 0xFF44
#define CGBL_VIDEO_LINE_Y_COINCIDENCE 0xFF45
#define CGBL_VIDEO_PALETTE_BACKGROUND 0xFF47
#define CGBL_VIDEO_PALETTE_BACKGROUND_CONTROL 0xFF68
#define CGBL_VIDEO_PALETTE_BACKGROUND_DATA 0xFF69
#define CGBL_VIDEO_PALETTE_OBJECT_0 0xFF48
#define CGBL_VIDEO_PALETTE_OBJECT_1 0xFF49
#define CGBL_VIDEO_PALETTE_OBJECT_CONTROL 0xFF6A
#define CGBL_VIDEO_PALETTE_OBJECT_DATA 0xFF6B
#define CGBL_VIDEO_RAM_BEGIN 0x8000
#define CGBL_VIDEO_RAM_END 0x9FFF
#define CGBL_VIDEO_RAM_OBJECT_BEGIN 0xFE00
#define CGBL_VIDEO_RAM_OBJECT_END 0xFE9F
#define CGBL_VIDEO_RAM_SELECT 0xFF4F
#define CGBL_VIDEO_SCROLL_X 0xFF43
#define CGBL_VIDEO_SCROLL_Y 0xFF42
#define CGBL_VIDEO_STATUS 0xFF41
#define CGBL_VIDEO_TRANSFER_CONTROL 0xFF55
#define CGBL_VIDEO_TRANSFER_DESTINATION_HIGH 0xFF53
#define CGBL_VIDEO_TRANSFER_DESTINATION_LOW 0xFF54
#define CGBL_VIDEO_TRANSFER_OBJECTS 0xFF46
#define CGBL_VIDEO_TRANSFER_SOURCE_HIGH 0xFF51
#define CGBL_VIDEO_TRANSFER_SOURCE_LOW 0xFF52
#define CGBL_VIDEO_WIDTH 160
#define CGBL_VIDEO_WINDOW_X 0xFF4B
#define CGBL_VIDEO_WINDOW_Y 0xFF4A

#define CGBL_VIDEO_RAM_WIDTH \
    CGBL_WIDTH(CGBL_VIDEO_RAM_BEGIN, CGBL_VIDEO_RAM_END)
#define CGBL_VIDEO_RAM_OBJECT_WIDTH \
    (CGBL_WIDTH(CGBL_VIDEO_RAM_OBJECT_BEGIN, CGBL_VIDEO_RAM_OBJECT_END) / sizeof (cgbl_object_t))

typedef enum {
    CGBL_COLOR_WHITE = 0,
    CGBL_COLOR_GREY_LIGHT,
    CGBL_COLOR_GREY_DARK,
    CGBL_COLOR_BLACK,
    CGBL_COLOR_MAX,
} cgbl_color_e;

const uint16_t (*cgbl_video_color(void))[CGBL_VIDEO_HEIGHT][CGBL_VIDEO_WIDTH];
uint8_t cgbl_video_read(uint16_t address);
void cgbl_video_reset(void);
cgbl_error_e cgbl_video_step(void);
void cgbl_video_write(uint16_t address, uint8_t data);

#endif /* CGBL_VIDEO_H_ */
